spring:
  application:
    name: ValidationDojo

  datasource:
    url: jdbc:sqlite:validationdojo.db
    driver-class-name: org.sqlite.JDBC
    username: root
    password: secret

  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

  doc:
    api-docs:
      path: /api-docs

server:
  port: 5003
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: Pass123$
    key-store-type: PKCS12
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto